# Generated by Django 3.2.2 on 2021-05-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endereco',
            new_name='Enderecos',
        ),
    ]
