# Generated by Django 3.2.2 on 2021-05-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_endereco_enderecos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='estado',
            field=models.CharField(max_length=100, verbose_name='Estado'),
        ),
    ]
